---
AWSTemplateFormatVersion: '2010-09-09'
Description: Data provider for AWS services

Parameters:
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Route53 Hosted Zone ID
  DNSName:
    Type: String
    Description: Route53 Hosted DNS Name
  Version:
    Type: Number
    Description: "Just for testing"
    Default: 1
  SubnetCidr:
    Type: String
    Description: "The CIDR of subnet to be found"
    Default: 172.31.32.0/20

Resources:
  ZoneInfoBaseOnID:
    Type: Custom::R53HostedZone
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub "cfn:cfn-dataprovider:${AWS::Region}:arn"
      Filter:
        HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Version
          Value: !Ref Version

  ZoneInfoBasedOnName:
    Type: Custom::R53HostedZone
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub "cfn:cfn-dataprovider:${AWS::Region}:arn"
      Filter:
        DNSName: !Ref DNSName
        PrivateZone: False
      Tags:
        - Key: Version
          Value: !Ref Version

  SubnetInfo:
    Type: Custom::Subnet
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub "cfn:cfn-dataprovider:${AWS::Region}:arn"
      Filter:  # For more options check https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_subnets
        cidr: !Ref SubnetCidr
        state: available
        #tag-key: blue
        #"tag:Name": subnetname
      Tags:
        - Key: Version
          Value: !Ref Version

  VPCInfo:
    Type: Custom::VPC
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub "cfn:cfn-dataprovider:${AWS::Region}:arn"
      Filter:  # For more options check https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_vpcs
        vpc-id: !GetAtt SubnetInfo.VpcId

Outputs:
  HostedZoneName:
    Description: "Hosted Zone Name"
    Value: !GetAtt ZoneInfoBaseOnID.HostedZone.Name
  HostedZoneRecords:
    Description: "Number of Records"
    Value: !GetAtt ZoneInfoBaseOnID.HostedZone.ResourceRecordSetCount
  PrivateZone:
    Description: "Is that private zone"
    Value: !GetAtt ZoneInfoBasedOnName.HostedZone.Config.PrivateZone
  SubnetID:
    Description: "SubnetID"
    Value: !Ref SubnetInfo
  VPCId:
    Description: "The VPC where this subnet is"
    Value: !GetAtt SubnetInfo.VpcId
  AvailabilityZone:
    Description: "The AvailabilityZone for this subnet"
    Value: !GetAtt SubnetInfo.AvailabilityZone
  IsVPCDefault:
    Description: "Is that VPC the default"
    Value: !GetAtt VPCInfo.IsDefault
